"""Fine-tune YOLOv8 on validated MTG card patches from the dataset.

Exports validated detections from dataset.db as a YOLO training dataset and
fine-tunes a YOLOv8 model.  The more patches users validate via the
Karten-Zuordnung tab, the better the model becomes over time.

Usage:
    python scripts/train_yolo.py                          # Default settings
    python scripts/train_yolo.py --epochs 50              # Fewer epochs
    python scripts/train_yolo.py --base-model yolov8s.pt  # Larger base model
    python scripts/train_yolo.py --dry-run                # Show dataset stats

Workflow:
    1. User scans images → patches saved to data/patches/
    2. User validates patches in Karten-Zuordnung tab → scryfall_id assigned
    3. Run this script → exports YOLO dataset + fine-tunes YOLOv8
    4. New model saved to data/models/yolo_mtg.pt
    5. Set detection.method: yolo in config.yaml to use it
"""

from __future__ import annotations

import argparse
import logging
import shutil
import sqlite3
import sys
from pathlib import Path

logger = logging.getLogger(__name__)

_DATA_DIR = Path("data")
_MODELS_DIR = _DATA_DIR / "models"
_TRAINING_DIR = _DATA_DIR / "yolo_training"


def _export_yolo_dataset(
    dataset_db: str = "data/dataset.db",
    output_dir: Path = _TRAINING_DIR,
    val_split: float = 0.15,
    min_confidence: float = 0.0,
) -> dict:
    """Export validated patches from dataset.db as a YOLO training dataset.

    Creates the standard YOLO directory layout:
        data/yolo_training/
            images/train/, images/val/
            labels/train/, labels/val/
            dataset.yaml

    Args:
        dataset_db: Path to the dataset SQLite database.
        output_dir: Root output directory.
        val_split: Fraction of data to use for validation (default 0.15).
        min_confidence: Minimum recognition confidence to include a patch.

    Returns:
        Dict with dataset statistics.
    """
    import cv2
    import numpy as np

    db_path = Path(dataset_db)
    if not db_path.exists():
        raise FileNotFoundError(f"Dataset DB not found: {dataset_db}")

    conn = sqlite3.connect(dataset_db)

    # Fetch all detections with source image + bounding box
    rows = conn.execute("""
        SELECT
            s.image_path,
            d.bbox_x, d.bbox_y, d.bbox_w, d.bbox_h,
            d.patch_image_path,
            r.confidence,
            r.card_name
        FROM detections d
        JOIN scans s ON d.scan_id = s.id
        LEFT JOIN results r ON r.detection_id = d.id
        WHERE d.bbox_w > 0 AND d.bbox_h > 0
        ORDER BY s.id, d.patch_index
    """).fetchall()
    conn.close()

    if not rows:
        return {"total": 0, "train": 0, "val": 0, "skipped": 0}

    # Filter by confidence
    valid = [r for r in rows if (r[6] or 0.0) >= min_confidence]
    skipped = len(rows) - len(valid)

    # Split train / val
    import random
    random.shuffle(valid)
    split_idx = max(1, int(len(valid) * (1 - val_split)))
    train_rows = valid[:split_idx]
    val_rows = valid[split_idx:]

    # Create directory structure
    for split in ("train", "val"):
        (output_dir / "images" / split).mkdir(parents=True, exist_ok=True)
        (output_dir / "labels" / split).mkdir(parents=True, exist_ok=True)

    def _write_split(rows_subset, split: str) -> int:
        from mtg_scanner.utils.image_utils import load_image
        written = 0
        for idx, row in enumerate(rows_subset):
            img_path, bx, by, bw, bh, patch_path, conf, name = row
            src = Path(img_path)
            if not src.exists():
                continue

            img = load_image(str(src))
            if img is None:
                continue

            ih, iw = img.shape[:2]
            if iw == 0 or ih == 0:
                continue

            # YOLO format: class cx cy w h (all normalised 0-1)
            cx = (bx + bw / 2) / iw
            cy = (by + bh / 2) / ih
            nw = bw / iw
            nh = bh / ih

            # Clamp to valid range
            cx = max(0.0, min(1.0, cx))
            cy = max(0.0, min(1.0, cy))
            nw = max(0.001, min(1.0, nw))
            nh = max(0.001, min(1.0, nh))

            stem = f"{src.stem}_{idx:04d}"
            img_out = output_dir / "images" / split / f"{stem}.jpg"
            lbl_out = output_dir / "labels" / split / f"{stem}.txt"

            cv2.imwrite(str(img_out), img, [cv2.IMWRITE_JPEG_QUALITY, 90])
            with open(lbl_out, "w") as f:
                f.write(f"0 {cx:.6f} {cy:.6f} {nw:.6f} {nh:.6f}\n")

            written += 1
        return written

    train_written = _write_split(train_rows, "train")
    val_written = _write_split(val_rows, "val")

    # Write dataset.yaml
    yaml_content = f"""# MTG Card Scanner — YOLO training dataset
# Auto-generated by scripts/train_yolo.py

path: {output_dir.resolve()}
train: images/train
val:   images/val

nc: 1
names:
  0: mtg_card
"""
    (output_dir / "dataset.yaml").write_text(yaml_content)

    return {
        "total": len(valid),
        "train": train_written,
        "val": val_written,
        "skipped": skipped,
        "dataset_yaml": str(output_dir / "dataset.yaml"),
    }


def train(
    base_model: str = "yolov8n.pt",
    epochs: int = 100,
    imgsz: int = 640,
    batch: int = 16,
    output_model: str = "data/models/yolo_mtg.pt",
    dataset_db: str = "data/dataset.db",
    val_split: float = 0.15,
    min_confidence: float = 0.0,
) -> str:
    """Export dataset and fine-tune YOLOv8.

    Args:
        base_model: YOLOv8 base model to start from (e.g. ``yolov8n.pt``).
        epochs: Number of training epochs.
        imgsz: Input image size (pixels).
        batch: Batch size (-1 = auto).
        output_model: Where to copy the final model.
        dataset_db: Path to dataset.db with validated patches.
        val_split: Fraction of data for validation.
        min_confidence: Minimum recognition confidence to include a detection.

    Returns:
        Path to the saved model.
    """
    try:
        from ultralytics import YOLO  # type: ignore
    except ImportError:
        raise ImportError(
            "The 'ultralytics' package is required for YOLO training.\n"
            "Install it with:  pip install 'mtg-card-scanner[yolo]'\n"
            "or:               pip install ultralytics"
        )

    # 1. Export dataset
    print("Exporting YOLO training dataset from dataset.db …")
    stats = _export_yolo_dataset(
        dataset_db=dataset_db,
        output_dir=_TRAINING_DIR,
        val_split=val_split,
        min_confidence=min_confidence,
    )
    print(
        f"  Dataset: {stats['total']} patches "
        f"({stats['train']} train / {stats['val']} val, {stats['skipped']} skipped)"
    )

    if stats["train"] < 10:
        raise RuntimeError(
            f"Not enough training images ({stats['train']} found, need at least 10).\n"
            "Validate more patches via the Karten-Zuordnung tab first."
        )

    dataset_yaml = stats["dataset_yaml"]

    # 2. Load base model
    print(f"Loading base model: {base_model} …")
    model = YOLO(base_model)

    # 3. Fine-tune
    print(f"Training for {epochs} epochs (imgsz={imgsz}, batch={batch}) …")
    results = model.train(
        data=dataset_yaml,
        epochs=epochs,
        imgsz=imgsz,
        batch=batch,
        project=str(_TRAINING_DIR / "runs"),
        name="yolo_mtg",
        exist_ok=True,
        verbose=True,
    )

    # 4. Copy best model to output location
    _MODELS_DIR.mkdir(parents=True, exist_ok=True)
    best = Path(results.save_dir) / "weights" / "best.pt"
    if best.exists():
        shutil.copy2(best, output_model)
        print(f"\nModel saved to: {output_model}")
    else:
        print(f"Warning: best.pt not found at {best}. Check training output.")
        output_model = str(Path(results.save_dir) / "weights" / "last.pt")

    return output_model


def dry_run(dataset_db: str = "data/dataset.db") -> str:
    """Show training dataset statistics without training."""
    db_path = Path(dataset_db)
    if not db_path.exists():
        return f"Dataset DB not found: {dataset_db}"

    conn = sqlite3.connect(dataset_db)
    total_scans = conn.execute("SELECT COUNT(*) FROM scans").fetchone()[0]
    total_det = conn.execute(
        "SELECT COUNT(*) FROM detections WHERE bbox_w > 0"
    ).fetchone()[0]
    validated = conn.execute(
        "SELECT COUNT(*) FROM results WHERE scryfall_id IS NOT NULL"
    ).fetchone()[0]
    conn.close()

    train_count = int(total_det * 0.85)
    val_count = total_det - train_count
    est_time = total_det * 0.5 / 60  # rough estimate

    lines = [
        "Dry Run — YOLO Training",
        f"  Scans in DB:           {total_scans}",
        f"  Detektionen gesamt:    {total_det}",
        f"  Davon validiert:       {validated}",
        f"  Train / Val split:     {train_count} / {val_count} (85/15)",
        f"  Geschätzte Trainingszeit: ~{est_time:.0f} min (ohne GPU)",
        "",
        "Nächste Schritte:",
        "  1. Mehr Karten in der Karten-Zuordnung tab validieren",
        "  2. Dieses Skript ausführen",
        "  3. detection.method: yolo in config.yaml setzen",
    ]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Fine-tune YOLOv8 on validated MTG card patches."
    )
    parser.add_argument("--base-model", default="yolov8n.pt",
                        help="YOLOv8 base model (e.g. yolov8n.pt, yolov8s.pt)")
    parser.add_argument("--epochs", type=int, default=100)
    parser.add_argument("--imgsz", type=int, default=640)
    parser.add_argument("--batch", type=int, default=16)
    parser.add_argument("--output-model", default="data/models/yolo_mtg.pt")
    parser.add_argument("--dataset-db", default="data/dataset.db")
    parser.add_argument("--val-split", type=float, default=0.15)
    parser.add_argument("--min-confidence", type=float, default=0.0)
    parser.add_argument("--dry-run", action="store_true", help="Show stats, don't train")
    args = parser.parse_args()

    logging.basicConfig(
        format="%(asctime)s [%(levelname)s] %(message)s", level=logging.INFO
    )

    if args.dry_run:
        print(dry_run(args.dataset_db))
        return

    try:
        model_path = train(
            base_model=args.base_model,
            epochs=args.epochs,
            imgsz=args.imgsz,
            batch=args.batch,
            output_model=args.output_model,
            dataset_db=args.dataset_db,
            val_split=args.val_split,
            min_confidence=args.min_confidence,
        )
        print(f"\nTraining complete. Model: {model_path}")
        print("Setze in config.yaml:  detection.method: yolo")
    except Exception as exc:
        print(f"Error: {exc}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
